anguageCode = "en-us"
title = "Dave Parr"
baseurl = "daveparr.info"
theme = "prologue"

[params]
  name = "Dave Parr"
  description = "Make, Do and Mend"
  copyright = "Untitled."

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/daveparr"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "https://www.instagram.com/davergparr/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/DaveParr"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/davidrgparr/"

# Portfolio column one

[[params.portfolio1]]
  title = "Tales From The Makery"
  source = "img/talesFromTheMakery.jpg"
  url = "https://www.youtube.com/channel/UCcJL7jIMFig2119tYpy8TsQ"

# Portfolio column two

[[params.portfolio2]]
  title = "Cardiff R User Group"
  source = "img/caRdiffR.png"
  url = "https://www.meetup.com/Cardiff-R-User-Group/"

[[params.portfolio2]]
  title = "Noun Project R api"
  source = "img/r.jpg"
  url = "https://github.com/CaRdiffR/nounprojectR"

[[params.portfolio2]]
  title = "Trans Day of Rememberance R data package"
  source = "img/r.jpg"
  url = "https://github.com/CaRdiffR/tdor/"

# Portfolio column 3

[[params.portfolio3]]
  title = "SatRdays Cardiff"
  source = "img/satRdayLogo-square.png"
  url = "https://cardiff2018.satrdays.org/"

[[params.portfolio3]]
  title = "SatRdays hugo theme"
  source = "img/satrdays.png"
  url = "https://github.com/satRdays/hugo-satrdays-theme"


[[params.portfolio3]]
  title = "SatRday Budapest Talk"
  source = "img/budapest.jpg"
  url = "https://youtu.be/afVks_er01s"


